# Generated by Django 4.1.1 on 2022-10-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_mine', '0002_alter_category_options_alter_note_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Photo'),
        ),
    ]
