# Generated by Django 4.1.1 on 2022-10-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_mine', '0005_alter_note_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Please choose category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='notes_mine.category'),
        ),
    ]
